### ISSUE TITLE
INkiller wont sideload on my iPhone

### ISSUE THREAD

**Issue by 02Rusty** [iKarwan/iNKillerPlus#11]
### Describe the bug

```yaml
When sideloadly is uploading/installing the ipa to my iPhone it throws me this error as shown in the picture below.
```

### Steps to reproduce

```yaml
open sideloadly,
use latest ipa as shown in readme,
sideload,
error thrown.
```

### Crashlog

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/08b9ebe4-d729-478f-ba18-d4253218ea1c">

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by iKarwan** [comment]
hey i guess this error related to sideloadly pls install it with another service altstore or Esign

**Comment by 02Rusty** [comment]
tried using altstore and it gave me this longer error. 
<img width="853" alt="image" src="https://github.com/user-attachments/assets/767a05e2-3301-425e-8957-bd56814146d3">

**Comment by iKarwan** [comment]
cold u use any ipa for instagram decrypted and check !

**Comment by iKarwan** [comment]
i checked fresh insta ipa without any changes give same error only way i succeeded with was esign
