### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by jffortier249** [iKarwan/iNKillerPlus#12]
### Describe the bug

```yaml
Latest url not working for ipa/tipa
```

### Steps to reproduce

```yaml
Click and 🤷🏼‍♂️
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by iKarwan** [comment]
sorry fixed .
