### ISSUE TITLE
Add license to clipboard option

### ISSUE THREAD

**Issue by LucifersCircle** [iKarwan/iNKillerPlus#16]
### Describe the feature request

Hello, currently when your license is expired, and you try to log in, you get an alert that says "Restore Failed - License has expired". It would be nice to add another alert perhaps with an option to copy your key to the clipboard, so you can easily paste it in when you go to pay with stripe. I'm not sure what my key is anymore, I'll have to scour my email. On top of that I cant assign a new license so it would just be nice to be able to retrieve it in app somehow!

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by iKarwan** [comment]
sure
