### ISSUE TITLE
Cannot activate app with purchased code

### ISSUE THREAD

**Issue by vahotm** [iKarwan/iNKillerPlus#5]
I purchased activation code on March 23, and application worked fine until couple of days ago, when activation screen showed up again and didn't accept my code.

**Comment by LucifersCircle** [comment]
Sometimes it takes a couple tries. Leave the code inserted into the code box and push “Activate” if nothing happens after a few seconds, press “Reset” then just press “Activate” again. It can take a couple tries but always ends up working for me.

**Comment by iKarwan** [comment]
Hey 

Really sorry for the confusion I'm about to change that activation logic really
But i need some time for it and it'll be one time activation and no activation screen appears again
