### ISSUE TITLE
AltStore 

### ISSUE THREAD

**Issue by LucifersCircle** [iKarwan/iNKillerPlus#9]
### Describe the bug

```yaml
Get error message “File does not exist” when trying to install with the altstore link.
```

### Steps to reproduce

```yaml
Click altstore link in readme to open the ipa in altstore
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**

**Comment by iKarwan** [comment]
fixed in latest update
